#!/bin/sh

# Copyright 2022-2023 Yury Gribov
# 
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

# Format files from top commit

set -eu
set -x

cd $(git rev-parse --show-toplevel)
git show | grep '^diff' | awk '{print $4}' | cut -d/ -f2- | grep '\(\.c\|\.cpp\|\.cc\|\.hpp\|.h\|\.hh\)$' | xargs clang-format -i
