#!/bin/sh

# Copyright 2015-2018 Yury Gribov
# 
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

ctags --c++-kinds=+p --fields=+iaS --extra=+q --language-force=C++ "$@"
