#!/bin/sh

# Copyright 2017-2018 Yury Gribov
# 
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

if ctags --version 2>&1 | grep -q Emacs; then
  FLAGS='-l c++'
else
  # Exuberant Ctags
  FLAGS='--c++-kinds=+p --fields=+iaS --extra=+q --language-force=C++'
fi

ctags $FLAGS "$@"
