#!/bin/sh

# Copyright 2015-2016 Yury Gribov
# 
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

set -e

absolutize() {
  test -e "$1"
  (cd $(dirname "$1"); echo $PWD/$(basename "$1"))
}

error() {
  echo >&2 "$(basename $0): error: $@"
  exit 1
}

if test $# != 2; then
  error "Syntax: $(basename $0) dir1 dir2"
fi

if ! test -d "$1"; then
  error "Not a directory: $1"
fi

if ! test -d "$2"; then
  error "Not a directory: $2"
fi

d1=$(absolutize $1)
d2=$(absolutize $2)

cd $d1

for sum in $(find -name *.sum); do
  grep -v 'Test Run By\|home.ygribov' $sum > $sum.f || true
  grep -v 'Test Run By\|home.ygribov' $d2/$sum > $d2/$sum.f || true
  diff $sum.f $d2/$sum.f || true
done
