#!/bin/sh

# Copyright 2018-2022 Yury Gribov
# 
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

# Canonizes registers and immediates in objdump output for easier diffing

set -eu
set -x

sed -e '
  s/%[a-z0-9]\+/R/g
  s/0x[0-9a-fA-F]\+/IMM/g
  s/\<[0-9][0-9a-fA-F]*/IMM/g
'
