#!/bin/sh

# Copyright 2021-2022 Yury Gribov
# 
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

# Find all binary files in folder.

set -eu

find -L "$@" -type f -a ! -size 0 -print0 | xargs -0 grep -IL .
