#!/bin/sh -eu

# Copyright 2015-2017 Yury Gribov
# 
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

# Compares results of 2 GCC regression tests.

if [ $# != 1 -a $# != 2 ]; then
	echo "Syntax: `basename $0` REF-DIR [NEW-DIR]" >&2
	exit 1
fi

REF=$(cd $1; echo $PWD)

if [ $# = 1 ]; then
	NEW=$PWD
else
	NEW=$(cd $2; echo $PWD)
fi

SRC=$(dirname $(grep '^ \+\$.*configure' $1/config.log | head -1 | awk '{print $2}'))

for sum in $(cd $REF; find -name \*.sum); do
	echo "========== Comparing $sum"
	$SRC/contrib/dg-cmp-results.sh -v -v unix $REF/$sum $NEW/$sum
done

