#!/bin/sh

# Copyright 2020 Yury Gribov
# 
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

# Reset dates of N last commits.

set -eu
if set -o | grep -q pipefail; then set -o pipefail; fi

error() {
  echo >&2 "$(basename $0): error: $@"
  exit 1
}

if test $# != 1 -a $# != 2; then
  error "Syntax: $(basename $0) NUMCOMMITS [DATE]"
fi

N=$1
if test $# -lt 2; then
  D="$(date)"
fi

BRANCH=$(git rev-parse --abbrev-ref HEAD)
COMMITS=$(git show HEAD~$N..HEAD | awk '/^commit/{print $2}' | tac)

TMP_BRANCH=git-reset-dates-branch
git branch -D $TMP_BRANCH 2>/dev/null || true
git checkout -b $TMP_BRANCH HEAD~$N

for commit in $COMMITS; do
  git cherry-pick $commit
  git commit --amend --no-edit --date "$D"
done

git checkout $BRANCH
echo "Updated commits were saved in $TMP_BRANCH"
