#!/bin/sh

# Copyright 2020 Yury Gribov
# 
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

# Identify all shlibs used by files in folder

set -eu
if set -o | grep -q pipefail; then set -o pipefail; fi

if test $# = 0; then
  eval set -- "$PWD"
fi

# libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007fe9221d1000)
for f in $(find "$@" -type f -a -executable); do
  if file -b $f | grep -q ELF; then
    ldd $f
  fi
done | sed -ne '/=>/{ s/ *(0x.*//; p }' | sort -u
