#!/bin/sh

# Copyright 2019-2021 Yury Gribov
# 
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

# A simple wrapper for llvm-splitlog
# so that one can simply run:
#   $ llvm-collect-logs clang tmp.c -S
# or
#   $ llvm-collect-logs -o logs-new clang ...

set -eu

if test "${1:-}" = -o; then
  O=$2
  shift 2
else
  O=debug
fi

case "$1" in
*clang | *clang.exe)
  DEBUG_FLAGS='-mllvm -print-after-all'
  ;;
*llc | *llc.exe)
  DEBUG_FLAGS='-print-after-all'
  ;;
*)
  echo >&2 "Unknown executable: $1"
  exit 1
  ;;
esac

"$@" $DEBUG_FLAGS 2>$O.log || true
$(dirname $0)/llvm-splitlog.pl -o $O $O.log
