#!/bin/sh

# Copyright 2023 Yury Gribov
# 
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

# Indexes LLVM source code with ctags, respecting the supermacro, build directory
# and avoiding irrelevant files.

set -eu

if [ ! -f llvm/CMakeLists.txt ]; then
  echo 'You must run me from LLVM root directory' >&2
  exit 1
fi

rm -f cscope.* ctags tags

find llvm clang \
  -path llvm/test -prune -o -path clang/test -prune \
  -o \( -name \*.h -o -name \*.c -o -name \*.cpp \) -print > cscope.files

if test $# -ge 1; then
  BUILD=$1
else
  BUILD=$PWD/build
fi

if test -f "$BUILD/CMakeCache.txt"; then
  find $BUILD -name \*.inc -print >> cscope.files
else
  echo >&2 "Unable to find build directory at $BUILD, index may be incomplete"
fi

echo 'Building ctags database...'
ctags --c++-kinds=+p --fields=+iaS --extras=+q -a -L cscope.files

# TODO: merge contents of .def files
