#!/bin/sh
# Pylint wrapper which disables useless checks.

set -eu

log=$(basename $0).log
rm -f $log

for f in $(find -name \*.py); do
  pylint \
    -d bad-continuation \
    -d line-too-long \
    -d bad-indentation \
    -d bad-whitespace \
    -d invalid-name \
    -d too-many-locals \
    -d too-many-branches \
    -d too-many-statements \
    -d too-many-arguments \
    -d too-few-public-methods \
    -d too-many-instance-attributes \
    -d too-many-lines \
    -d missing-docstring \
    "$@" \
    $f | tee -a $log
done
echo "Copy of output was saved to $log"
