#!/bin/sh

# Copyright 2018 Yury Gribov
# 
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

# Pylint wrapper which disables useless checks
# and massages repo to satisfy pylint conventions.

set -eu

log=$(basename $0).log
rm -f $log

files=
for d in $(find -name \*.py  | xargs dirname | sort -u); do
  if ! test -f $d/__init__.py; then
    touch $d/__init__.py
    files="$files $PWD/$d/__init__.py"
  fi
done
trap "rm -f $files" EXIT INT TERM

name=$(basename $PWD)

cd ..
# PYTHONPATH used to avoid import-error warnings
# on 'from subfolder import submodule' statements
# in files in subfolders.
PYTHONPATH=$name${PYTHONPATH:+:$PYTHONPATH} pylint \
  --rcfile=$(dirname $0)/pylintrc
  "$@" \
  $name | tee -a $name/$log

echo "Copy of output was saved to $log"
