#!/bin/sh

# Copyright 2018 Yury Gribov
# 
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

# Pylint wrapper which disables useless checks
# and massages repo to satisfy pylint conventions.

set -eu

log=$(basename $0).log
rm -f $log

files=
for d in $(find -name \*.py  | xargs dirname | sort -u); do
  if ! test -f $d/__init__.py; then
    touch $d/__init__.py
    files="$files $PWD/$d/__init__.py"
  fi
done
trap "rm -f $files" EXIT

name=$(basename $PWD)

cd ..
# PYTHONPATH used to avoid import-error warnings
# on 'from subfolder import submodule' statements
# in files in subfolders.
PYTHONPATH=$name${PYTHONPATH:+:$PYTHONPATH} pylint \
  -d bad-continuation \
  -d line-too-long \
  -d bad-indentation \
  -d bad-whitespace \
  -d invalid-name \
  -d too-many-locals \
  -d too-many-branches \
  -d too-many-statements \
  -d too-many-arguments \
  -d too-few-public-methods \
  -d too-many-instance-attributes \
  -d too-many-lines \
  -d missing-docstring \
  -d misplaced-comparison-constant \
  "$@" \
  $name | tee -a $log

echo "Copy of output was saved to $log"
