#!/bin/sh

# Copyright 2018 Yury Gribov
# 
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

if ctags --version 2>&1 | grep -q Emacs; then
  FLAGS='-l python'
else
  # Exuberant Ctags
  FLAGS=--python-kinds=-i
fi

ctags $FLAGS "$@"
