#!/bin/sh

# Copyright 2015-2018 Yury Gribov
# 
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

set -eu

# Based on https://misc.flogisoft.com/bash/tip_colors_and_formatting
END_COLOR='\033[0m'
BLACK='\033[30m'
RED='\033[31m'
GREEN='\033[32m'
YELLOW='\033[33m'
BLUE='\033[34m'
MAGENTA='\033[35m'
CYAN='\033[36m'
WHITE='\033[97m'
UNDER='\033[2m'

absolutize() {
  test -e "$1"
  (cd "$(dirname "$1")"; echo $PWD/$(basename "$1"))
}

error() {
  prefix="error:"
  if test -t 2; then
    prefix="${RED}${prefix}${END_COLOR}"
  fi
  printf "$(basename $0): $prefix $@" >&2
  exit 1
}

warn() {
  prefix="warning:"
  if test -t 2; then
    prefix="${RED}${prefix}${END_COLOR}"
  fi
  printf "$(basename $0): $prefix $@" >&2
}

mkcleandir() {
  mkdir -p "$1"
  rm -rf "$1"/*
}

isemptydir() {
  #test $(ls -A "$1" | wc -l) = 0
  test -d "$1" && test "$(find "$1" -maxdepth 0 -empty)"
}

strip_ext() {
#  echo "$1" | sed -e 's!\.[^.]*$!!'
  echo "${1%.*}"
}

usage() {
  cat <<EOF
Usage: $(basename $0) [OPT]... ARG
<Tool description goes here>

Options:
  -h, --help    Print help and exit.
  -x            Enable shell tracing.
  <Other options go here>
EOF
  exit 1
}

me=$(basename $0)

ARGS=$(getopt -o 'o:hx' --long 'output:,help' -n "$(basename $0)" -- "$@")
eval set -- "$ARGS"

OUT=

while true; do
  case "$1" in
    -o | --output)
      OUT="$2"
      shift 2
      ;;
    -h | --help)
      usage
      ;;
    -x)
      set -x
      shift
      ;;
    --)
      shift
      break
      ;;
    -*)
      error "unknown option: $1"
      ;;
    *)
      error 'internal error'
      ;;
  esac
done

usage_short() {
  cat >&2 <<EOF
Usage: $(basename $0) [OPT]... ARG
Run \`$(basename $0) -h' for more details.
EOF
  exit
}

if [ $# -eq 0 ]; then
  usage_short
fi
