#!/bin/sh

# Copyright 2015-2018 Yury Gribov
# 
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

set -eu

absolutize() {
  test -e "$1"
  (cd $(dirname "$1"); echo $PWD/$(basename "$1"))
}

error() {
  echo >&2 "$(basename $0): error: $@"
  exit 1
}

warn() {
  echo >&2 "$(basename $0): warning: $@"
}

mkcleandir() {
  mkdir -p "$1"
  rm -rf "$1"/*
}

isemptydir() {
  #test $(ls -A "$1" | wc -l) = 0
  test -d "$1" && test $(find "$1" -maxdepth 0 -empty)
}

strip_ext() {
#  echo "$1" | sed -e 's!\.[^.]*$!!'
  echo "${1%.*}"
}

usage() {
  cat <<EOF
Usage: $(basename $0) [OPT]... ...
<Tool description goes here>

Options:
  -h, --help    Print help and exit.
  -x            Enable shell tracing.
  <Other options go here>
EOF
  exit 1
}

me=$(basename $0)

ARGS=$(getopt -o 'o:hx' --long 'output:,help' -n $(basename $0) -- "$@")
eval set -- "$ARGS"

OUTPUT=

while true; do
  case "$1" in
    -o | --output)
      OUTPUT="$2"
      shift 2
      ;;
    -h | --help)
      usage
      ;;
    -x)
      set -x
      ;;
    --)
      shift
      break
      ;;
    -*)
      error "unknown option: $1"
      ;;
    *)
      error 'internal error'
      ;;
  esac
done

if [ $# -eq 0 ]; then
  usage
fi
