#!/bin/sh

# Copyright 2021 Yury Gribov
# 
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

# Open straces of all child processes in editor.

set -eu

strace -ff -s1024 "$@" 2>&1 | ${EDITOR:-vim} -
