#!/bin/sh

# Copyright 2017 Yury Gribov
# 
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

set -eu

ME=$(basename $0)

absolutize() {
  test -e "$1"
  (cd $(dirname "$1"); echo $PWD/$(basename "$1"))
}

usage() {
  cat <<EOF
Syntax: $ME [OPT]... DIR
Update license comments in all source/script files in DIR.

Options:
  --license L, -l L  Path to main license file.
  -h, --help         Print this help and exit.
EOF
  exit 1
}

ARGS=$(getopt -o 'hl:' --long 'license:,help' -n $ME -- "$@")
eval set -- "$ARGS"

SHORT=
LICENSE=

while true; do
  case "$1" in
    -h | --help)
      usage
      ;;
    -l | --license)
      LICENSE=$2
      ;;
    --)
      shift
      break
      ;;
    -*)
      error "unknown option: $1"
      ;;
    *)
      error 'internal error'
      ;;
  esac
done

if test $# -eq 1; then
  DIR=$1
elif test $# -eq 0; then
  DIR=.
else
  echo >&2 "Usage: $ME [OPT]... DIR"
  exit 1
fi

if ! test -d "$DIR"; then
  echo >&2 "$ME: $DIR is not a directory"
  exit 1
fi

if ! test -d "$DIR"/.git; then
  echo >&2 "$ME: $DIR is not a git repo"
  exit 1
fi

if test -z "$LICENSE"; then
  LICENSE=$DIR/LICENSE.txt
  if ! test -f $LICENSE; then
    LICENSE=$DIR/LICENSE
  fi
fi

if ! test -f "$LICENSE"; then
  echo >&2 "$ME: can't open $LICENSE"
  exit 1
fi

update() {
  sed -i -e '
/Copyright\s/ {
  s/ \([0-9]\+-\)\?[0-9]\+[, ]/ '$2' /g;
}' $1
}

Y1=0
Y2=0
for f in $(find $DIR -iname '.[a-z0-9]*' -prune -o -type f -a -print); do
  d1=$(git log --follow --find-copies-harder --format=%ai $f | tail -n1)
  y1=$(date --date="$d1" +%Y)
  if test $Y1 = 0 -o $Y1 -gt $y1; then
    Y1=$y1
  fi

  d2=$(git log --follow --find-copies-harder --format=%ai $f | head -n1)
  y2=$(date --date="$d2" +%Y)
  if test $Y2 = 0 -o $Y2 -lt $y2; then
    Y2=$y2
  fi

  if test $y1 = $y2; then
    yy=$y1
  else
    yy="$y1-$y2"
  fi

  update $f "$yy"
done

if test $Y1 = 0 -o $Y2 = 0; then
  echo >&2 "$ME: failed to extract last modification date for $LICENSE"
  exit 1
fi

if test $Y1 = $Y2; then
  YY=$Y1
else
  YY="$Y1-$Y2"
fi

update $LICENSE "$YY"
