#!/usr/bin/python3

# Copyright 2017-2019 Yury Gribov
# 
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.
#
# Shortly describe script here.

import sys
import os
import os.path
import re
import subprocess
import argparse
import tempfile
import atexit

import imp, site

def ensure_module(module, package=None, user=True, quiet=False):
  """
  Installs module if it's missing. Call like
    ensure_module('configparser')
    ensure_module('wx', 'wxPython')
  """
  try:
    imp.find_module(module)
  except ImportError:
    if not quiet:
      print("Installing Python module %s..." % module)
    exe = sys.executable
    if package is None:
      package = module
    try:
      subprocess.check_call([exe, '-mensurepip'])
    except subprocess.CalledProcessError:
      warn("failed to ensure pip")
    subprocess.check_call(
      [exe, '-mpip', 'install'] + (['--user'] if user else []) + [package])
    # User site packages are often not in PATH by default
    for d in (site.getusersitepackages() if user else site.getsitepackages()):
      if d not in sys.path:
        sys.path.append(d)
    try:
      imp.find_module(module)
    except ImportError:
      error("module '%s' not found in package '%s'" % (module, package))

me = os.path.basename(__file__)

def warn(msg):
  sys.stderr.write('%s: warning: %s\n' % (me, msg))

def error(msg):
  sys.stderr.write('%s: error: %s\n' % (me, msg))
  sys.exit(1)

class Re:
  """
  "Regex cacher" gets rid of temporary match objects e.g.
    if Re.match(...):
      x = Re.group(1)
  """

  _last_match = None

  @classmethod
  def match(self, *args, **kwargs):
    self._last_match = re.match(*args, **kwargs)
    return self._last_match

  @classmethod
  def search(self, *args, **kwargs):
    self._last_match = re.search(*args, **kwargs)
    return self._last_match

  @classmethod
  def fullmatch(self, *args, **kwargs):
    self._last_match = re.fullmatch(*args, **kwargs)
    return self._last_match

  @classmethod
  def group(self, *args, **kwargs):
    return self._last_match.group(*args, *kwargs)

  @classmethod
  def groups(self, *args, **kwargs):
    return self._last_match.groups(*args, **kwargs)

def run(args, **kwargs):
  """A dummy wrapper to avoid deadlocks with subprocess.PIPE."""
  if 'abort_on_error' in kwargs:
    abort_on_error = kwargs['abort_on_error']
    del kwargs['abort_on_error']
  else:
    abort_on_error = False
  out_file = tempfile.mktemp()
  err_file = tempfile.mktemp()
  with open(out_file, 'w') as out_fileno, open(err_file, 'w') as err_fileno:
    p = subprocess.Popen(args, stdout=out_fileno, stderr=err_fileno, **kwargs)
    p.communicate()
  with open(out_file, 'r') as f:
    out = f.read()
  os.unlink(out_file)
  with open(err_file, 'r') as f:
    err = f.read()
  os.unlink(err_file)
  if p.returncode != 0 and abort_on_error:
    error("subprocess failed: %s\nStdout:\n%s\nStderr:\n%s" % (" ".join(args), out, err))
  return p, out, err

def main():
  parser = argparse.ArgumentParser(description="Describe script here.",
                                   formatter_class=argparse.RawDescriptionHelpFormatter,
                                   epilog="""\
Examples:
  $ python {0} arg
""".format(me))
  parser.add_argument('--flag', '-f',
                      help="Describe flag here.",
                      dest='flag', action='store_true', default=False)
  parser.add_argument('--no-flag',
                      help="Inverse of --flag.",
                      dest='flag', action='store_false')
  parser.add_argument('--param', '-p',
                      help="Describe scalar parameter here.",
                      default='0')
  parser.add_argument('--multi', '-m',
                      help="Describe array parameter here (can be specified more than once).",
                      action='append')
  parser.add_argument('--verbose', '-v',
                      help="Print diagnostic info (can be specified more than once).",
                      action='count', default=0)
  parser.add_argument('arg',
                      help="First positional argument.", metavar='ARG')
  parser.add_argument('rest',
                      nargs=argparse.REMAINDER, default=[])

  args = parser.parse_args()

  test_file = tempfile.mktemp()
  atexit.register(lambda: os.unlink(test_file))

  # TODO

  return 0

if __name__ == '__main__':
  sys.exit(main())
